# In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @ tf.function (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try yourself

# Introduction to Tensors

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimenstions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10, 17],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 17],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 9.],
                              [8., 7.],
                              [1., 4]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  9.],
       [ 8.,  7.],
       [ 1.,  4.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

# Creating tensors with `tf.constant`

In [10]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17 ,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. windspeed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (n can be any number)

# Creating tensors with `tf.Variable`

In [12]:
changeable_variable = tf.Variable([10,7])
unchangeable_variable = tf.constant([10,7])
changeable_variable, unchangeable_variable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

tf.Variable : changeable variable

tf.constant : unchangeable variable

In [13]:
# let's try changing one of the elements in the changeable tensor
changeable_variable[0].assign(1)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([1, 7])>

# Creating Random Tensors
Random tensors are tensors of some arbitrary size which contain random numbers.

In [14]:
# Generating two numbers ( but the same ) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle the order of elements in a tensor

In [15]:
tf.random.set_seed(42)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [1, 2]])
shuffled = tf.random.shuffle(not_shuffled)

In [16]:
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 1,  2],
       [10,  7]])>

In [17]:
tf.random.set_seed(42)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [1, 2]])
shuffled = tf.random.shuffle(not_shuffled, seed=42)

In [18]:
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 1,  2]])>

**EXERCISE**: Read Through TensorFlow Docs on random seed generation:
and practice writing 4 random tensors and shuffle them.

In [19]:
g1 = tf.random.Generator.from_seed(42)
g1 = g1.normal(shape=[2,3])
shuffled_g1 = tf.random.shuffle(g1)
shuffled_g1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-1.2573844 , -0.23193765, -1.8107855 ],
       [-0.7565803 , -0.06854702,  0.07595026]], dtype=float32)>

In [20]:
tf.random.set_seed(42)
g2 = tf.random.uniform([3,2])
g2_shuffled = tf.random.shuffle(g2)
g2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.6645621 , 0.44100678],
       [0.3528825 , 0.46448255],
       [0.03366041, 0.68467236]], dtype=float32)>

In [21]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
A = tf.constant(numpy_A, shape=(3,8))
B = tf.constant(numpy_A,)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### Getting information from tensors
* **Shape** : The length (number of elements) of each of the dimensions of a tensor. **`tensor.shape`**
* **Rank** : The number of tensor dimensions. A scalar has rank 0, vector has rank 1, a matrix has rank 2, and a tensor has rank n. **`tensor.ndim`**
* **Axis** or dimension : A particular dimension of a tensor. **`tensor[0], tensor[:,1]...`**
* **Size** : The total number of items in the tensor **`tf.size(tensor)`**

In [23]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [25]:
print('Datatype of every element: ', rank_4_tensor.dtype)
print('Number of dimensions (rank): ', rank_4_tensor.ndim)
print('Shape of Tensor: ', rank_4_tensor.shape)
print('Elements along the 0 axis: ', rank_4_tensor.shape[0])
print('Elements along the last axis', rank_4_tensor.shape[-1])
print('The total number of elements in our tensor: ', tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of Tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis 5
The total number of elements in our tensor:  120


In [26]:
# get the first two elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# get the first elements from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# create a rank 2 tensor which has 2 dimensions
rank_2_tensor = tf.constant([[10, 6],
                            [3, 4]])

In [29]:
# get the last item of each row of out rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 4])>

In [30]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 6]],

       [[ 3],
        [ 4]]])>

In [31]:
print('Datatype of every element: ', rank_3_tensor.dtype)
print('Number of dimensions (rank): ', rank_3_tensor.ndim)
print('Shape of Tensor: ', rank_3_tensor.shape)
print('Elements along the 0 axis: ', rank_3_tensor.shape[0])
print('Elements along the last axis', rank_3_tensor.shape[-1])
print('The total number of elements in our tensor: ', tf.size(rank_3_tensor).numpy())

Datatype of every element:  <dtype: 'int32'>
Number of dimensions (rank):  3
Shape of Tensor:  (2, 2, 1)
Elements along the 0 axis:  2
Elements along the last axis 1
The total number of elements in our tensor:  4


# Algebra with Tensors

In [32]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
#tensor + 10
tf.math.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [33]:
tensor - 10
tf.math.subtract(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

### Matrix multiplication, 
To multiply an **m×n** matrix by an **n×p** matrix, the **n**'s must be the same,
and the result is an **m×p** matrix.
(**m**×n) × (n×**p**) -> **m×p**

In [34]:
tensor_2 = tf.constant([[5, 4],
                        [15, 5]])
tf.matmul(tensor, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[155,  75],
       [ 75,  32]])>

In [35]:
tensor = tf.constant([[1,2,5],
                      [7,2,1],
                      [3,3,3]])
tensor_2 = tf.constant([[3,5],
                        [6,7],
                        [1,8]])
tf.matmul(tensor, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [36]:
tf.matmul(tensor, tf.reshape(tensor_2, shape=(3,2)))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

### The dot product
Matrix multiplication is alse referred to as the dot product.
You can perfom matrix multiplication using:
   * tf.matmul()
   * tf.tensordot()

### Transpose and Reshape


As you can notice, **a** and **b** are different, though have the same shape. That's because the first reshaping **"splits" x into [3 5], [6 7] and [1 8], while the second reshaping into [3 6 1] and [5 7 8].**

In [37]:
tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]])>

In [38]:
tranposed_tensor = tf.transpose(tensor_2)
tranposed_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 6, 1],
       [5, 7, 8]])>

In [39]:
reshaped_tensor = tf.reshape(tensor_2, shape=(2,3))
reshaped_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]])>

## Changing the dtype of a tensor
use var = tf.cast(tensor, dtype=tf.)

In [40]:
C = tensor

In [41]:
C = tf.cast(C, dtype=tf.float16)
C, C.dtype


(<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
 array([[1., 2., 5.],
        [7., 2., 1.],
        [3., 3., 3.]], dtype=float16)>,
 tf.float16)

# Aggregating Tensors
Forms of Aggregation:
 * Get the minimum `tf.math.reduce_min(tensor)`
 * Get the maximum `tf.math.reduce_max(tensor)`
 * Get the mean of a tensor `tf.math.reduce_mean()`
 * Get the sum of a tensor `tf.math.reduce_max()`
 * Convert to Absolute value `tf.abs()`

In [42]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [43]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [44]:
something_random = shuffled_g1

In [45]:
tf.math.reduce_min(something_random)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.8107855>

In [46]:
tf.math.reduce_max(something_random)

<tf.Tensor: shape=(), dtype=float32, numpy=0.07595026>

In [47]:
tf.math.reduce_mean(something_random)

<tf.Tensor: shape=(), dtype=float32, numpy=-0.67488074>

In [48]:
tf.math.reduce_max(something_random)

<tf.Tensor: shape=(), dtype=float32, numpy=0.07595026>

## Finding the positional maximum and minimum

In [49]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [50]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [51]:
# find the positional maximum value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [52]:
# find the maximum value
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [53]:
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
            0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
            0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
            0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
            0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
            0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
            0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
            0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
            0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
            0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
       dtype=float32)>,
 TensorShape([1, 1, 1, 1, 50]))

In [54]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

# One hot encoding

In [55]:
# create a list of indices
some_list = [0,1,2,3]


In [56]:
# one hot encode our list of indices
tf.one_hot(some_list, depth=4)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [57]:
tf.one_hot(some_list, on_value='yo da yo', off_value='ehe', depth=4)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo da yo', b'ehe', b'ehe', b'ehe'],
       [b'ehe', b'yo da yo', b'ehe', b'ehe'],
       [b'ehe', b'ehe', b'yo da yo', b'ehe'],
       [b'ehe', b'ehe', b'ehe', b'yo da yo']], dtype=object)>

# Squaring, log, sqrt

In [59]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [60]:
tf.math.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [62]:
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [63]:
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [66]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [67]:
!nvidia-smi

Wed May  5 11:24:05 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 466.11       Driver Version: 466.11       CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:09:00.0  On |                  N/A |
| 40%   53C    P0    32W / 160W |   3991MiB /  6144MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------